---
fixtures:
  repositories:
    apache:
      repo: https://github.com/simp/pupmod-simp-apache
      branch: 5.X
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      branch: 5.X
    augeasproviders:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders
    augeasproviders_base:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_base
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_grub
    augeasproviders_puppet:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_puppet
    augeasproviders_apache:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_apache
    augeasproviders_mounttab:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_mounttab
    augeasproviders_nagios:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_nagios
    augeasproviders_pam:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_pam
    augeasproviders_postgresql:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_postgresql
    augeasproviders_shellvar:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_shellvar
    augeasproviders_ssh:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_ssh
    augeasproviders_sysctl:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_sysctl
    compliance_markup:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      branch: 5.X
    haveged:
      branch: 5.X
      repo: https://github.com/simp/puppet-haveged
    inifile:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-inifile
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: 5.X
    logrotate:
      repo: https://github.com/simp/pupmod-simp-logrotate
      branch: 5.X
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
      branch: 5.X
    pam:
      repo: https://github.com/simp/pupmod-simp-pam
      branch: 5.X
    pupmod:
      repo: https://github.com/simp/pupmod-simp-pupmod
      branch: 5.X
    postgresql:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-postgresql
    oddjob:
      repo: https://github.com/simp/pupmod-simp-oddjob
      branch: 5.X
    openldap:
      repo: https://github.com/simp/pupmod-simp-openldap
      branch: 5.X
    rsync:
      repo: https://github.com/simp/pupmod-simp-rsync
      branch: 5.X
    rsyslog:
      repo: https://github.com/simp/pupmod-simp-rsyslog
      branch: 5.X
    simp:
      repo: https://github.com/simp/pupmod-simp-simp
      branch: 5.X
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    simpcat:
      repo: https://github.com/simp/pupmod-simp-simpcat
      branch: 5.X
    sssd:
      repo: https://github.com/simp/pupmod-simp-sssd
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
    tcpwrappers:
      repo: https://github.com/simp/pupmod-simp-tcpwrappers
      branch: 5.X
  symlinks:
    foreman: "#{source_dir}"
